services:
  spot-ros2-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: spot-ros2-base
    container_name: spot_ros2
  spot-ros2-development:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: berria
    volumes:
      - ./spot_driver/config/spot_ros_example.yaml:/ros_ws/src/robot.yaml
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY  # For GUI (if using RViz, etc.)
      - SPOT_LIDAR_MOUNT=1
      - SPOT_VELODYNE=1
      - SPOT_PACK=1
      # Default value, can be set via CLI with >>SPOT_NAME=spot docker compose up<<
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash && 
        source /ros_ws/install/setup.bash && 
        ros2 launch spot_driver spot_driver.launch.py config_file:=/ros_ws/src/robot.yaml launch_rviz:=True
      "

      #         ros2 launch spot_driver spot_driver.launch.py config_file:=/ros_ws/src/robot.yaml launch_rviz:=False
# ros2 launch spot_ros2_control spot_ros2_control.launch.py hardware_interface:=mock
